title: nucular writes
description: I write text n shit

baseurl: "/blog"
url: "https://nucular.github.io"

author:
  name: nucular
  fullname: Jakob E
  github: nucular
  twitter: nucularer
  reddit: nucular_
  keybase: nucular

disqus: nucblog

gems:
  - jekyll-sitemap
highlighter: pygments
sass:
  sass_dir: css/partials
  theme: dark
