---
title: nucular writes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: I write text n shit
baseurl: "/blog"
url: https://nucular.github.io
repo: https://github.com/nucular/blog
author:
  name: nucular
  fullname: Jakob E
  github: nucular
  twitter: nucularer
  reddit: nucular_
  keybase: nucular
disqus: nucblog
gems:
- jekyll-sitemap
highlighter: pygments
sass:
  sass_dir: css/partials
  theme: light
